config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'

  get 'welcome/index'

  resources :listings, controller: "listings"
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create,:profile] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  # get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  # delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  # get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

post 'braintree/:id' => "braintree#checkout"
get 'braintree/:id' => "braintree#new"

get "/reservation" => "reservations#index"
get "/listings/:id/reservation/new" => "reservations#new"
get "reservation/host" => "reservations#find"
post "/listings/:id/reservation/new" => "reservations#create"


post "/profile/edit" => "users#update"
get "/profile" => 'users#edit'
get "/listings/:id/preview" => "listings#preview"
post "/listings/:id" => "listings#show"
post "/listings/:id/verify" => "listings#verify"
get "/auth/:provider/callback" => "sessions#create_from_omniauth"

post "/search" => "listings#search"

##this is to link to google for sign in with google
root to: "home#index"
##this is to point the rootpage to view/home/index.. every time to create a view, need to create a controller. 
##home is the class while index is the method. the naming should be the same for the views folder
end

app/models/listing.rb
class Listing < ApplicationRecord
	include Filterable 
	include PgSearch
	pg_search_scope :search_by_country, :against => :state
	belongs_to :user
	has_many :reservations, :dependent => :destroy
	mount_uploaders :property, ImageUploader


	def self.search_country(query)
		where("state ILIKE :state", state: "%#{query}%").map do |record|
			record.state
		end
	end 

	self.per_page = 32
  
end

WillPaginate.per_page = 32

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
 
  # GET /listings
  # GET /listings.json

  def search
    if params[:query].present?
       @listing = Listing.search_country(params[:query])
       @list = Listing.search_by_country(params[:query])

       respond_to do |format|
          # format.html
          format.json {render json: @listing}
          # format.js
         end
      else
      @list = Listing.all
      end

     
  end

   def index
      @listing = Listing.all
   end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new

	end

 def edit
  	@listing= Listing.find(params[:id])
  	if current_user.id != @listing.user_id
        flash[:notice] 
        return redirect_to listings_url, notice:"Sorry. You are not allowed to perform this action."
      end
  end

  def verify
  	if current_user.moderator?
  		@listing = Listing.find(params[:id])
  		@listing.update(verification: true)
  		flash[:notice]
  		return redirect_to listings_url, notice: "The property #{@listing.id} has been verified"
  	else
  		flash[:notice]
  		return redirect_to listings_url, notice: "Sorry. You are not allowed to perform this action."
  	end
  end

  # POST /listings
  # POST /listings.json
  def create
  	if current_user.customer?
	    @listing = Listing.new(listing_params)

	    respond_to do |format|
	      if @listing.save
	        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
	        format.json { render :show, status: :created, location: @listing }
	      else
	        format.html { render :new }
	        format.json { render json: @listing.errors, status: :unprocessable_entity }
	      end
	    end
	end
  end




  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update

    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
  	@listing= Listing.find(params[:id])
  	user = User.all
	  	if current_user.id == @listing.user_id || current_user.admin?
        @listing.destroy
          respond_to do |format|
          format.js 
  		    format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
  		    format.json { head :no_content }
		   	  end
		  else
		 	  flash[:notice]
		 	  return redirect_to listings_url,notice: 'Sorry. You are not allowed to perform this action'
		  end
  end

  def preview
    @listing = Listing.find(params[:id])
    @image = @listing.property[0] 
    respond_to do |format|
      format.json {render json: @image}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :place_type, :property_type, :room_number, :bed_number, :guest_number, :country, :state, :city, :zipcode, :address, :price, :description, :user_id, property: [])
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(listing) do |f| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :property_type %>
    <%= f.text_field :property_type %>
  </div>

  <div class="field">
    <%= f.label :room_number %>
    <%= f.number_field :room_number %>
  </div>

  <div class="field">
    <%= f.label :bed_number %>
    <%= f.number_field :bed_number %>
  </div>

  <div class="field">
    <%= f.label :guest_number %>
    <%= f.number_field :guest_number %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :zipcode %>
    <%= f.number_field :zipcode %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>



    <div class="field">
    <%= f.label :property %>
    <%= f.file_field :property,multiple: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/destroy.js.erb
console.log("deleted");

$("#listing_<%= @listing.id%>").fadeOut()

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
 <h3 id="location">Enter the location that you looking for</h3>


    <%= form_tag '/search', method: 'post', :id => 'form', :class => 'form-inline my-2 my-lg-0' do %>
     <%= text_field_tag :query, "", :class =>'form-control mr-sm-2', list: "list" %>
     <datalist id="list"> 
    </datalist>
      <%= submit_tag "Search",:id => 'searchBtn',:class => 'btn btn-outline-primary my-2 my-sm-0'%>
      <% end %>

<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Property type</th>
      <th>Room number</th>
      <th>Bed number</th>
      <th>Guest number</th>
      <th>Country</th>
      <th>State</th>
      <th>City</th>
      <th>Zipcode</th>
      <th>Address</th>
      <th>Price</th>
      <th>Description</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if current_user.moderator?%>
      <% @listing.order('verification asc').each do |listing| %>
        <tr id = "listing_<%=listing.id%>">
            
            <td><%= listing.name %></td>
            <td><%= listing.property_type %></td>
            <td><%= listing.room_number %></td>
            <td><%= listing.bed_number %></td>
            <td><%= listing.guest_number %></td>
            <td><%= listing.country %></td>
            <td><%= listing.state %></td>
            <td><%= listing.city %></td>
            <td><%= listing.zipcode %></td>
            <td><%= listing.address %></td>
            <td><%= listing.price %></td>
            <td><%= listing.description %></td>

            <td><%= link_to 'Show', listing %></td>
            <% if listing.verification == false%>
            <td><%= button_to 'Verification',"/listings/#{listing.id}/verify", method: :post%></td>
            <%end%>
      <%end%>

    <%else%>
        <% @listing.order('id asc').each do |listing| %>
          <%if listing.verification == true%>
        <tr id = "listing_<%=listing.id%>">
            <td><%= listing.name %></td>
            <td><%= listing.property_type %></td>
            <td><%= listing.room_number %></td>
            <td><%= listing.bed_number %></td>
            <td><%= listing.guest_number %></td>
            <td><%= listing.country %></td>
            <td><%= listing.state %></td>
            <td><%= listing.city %></td>
            <td><%= listing.zipcode %></td>
            <td><%= listing.address %></td>
            <td><%= listing.price %></td>
            <td><%= listing.description %></td>

            
            <td><%= link_to 'Show', listing%></td>
            <td><%=link_to 'Preview', "/listings/#{listing.id}/preview",class: 'preview-btn', id: "#{listing.id}"%>
            <%if current_user.id == listing.user_id %>
            <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
            <td><%= link_to 'Destroy', listing, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>
            <%elsif current_user.admin?%>
            <td><%= link_to 'Destroy', listing, method: :delete, class: 'del-btns', id: "#{listing.id}",  data: { confirm: 'Are you sure?'} %></td>
            <%end%>
            
          </tr>
        <% end %>
      <%end%>
    <%end%>
    
  </tbody>
</table>
<div id="image-show"></div>
<br>
<% if current_user.customer?%>
<%= link_to 'New Listing', new_listing_path %>
<%end%>


<script type="text/javascript">

  $('.preview-btn').on('click', function(e) {
    console.log("clicked")
    e.preventDefault();
    $.ajax({
      url: `listings/${e.target.id}/preview`,
      method: 'get',
      dataType: 'JSON',
      success: function(data) {
        console.log(data);

        const imgUrl = data.url

        $('#image-show').append(`<img src="${imgUrl}"/>`) 
      },
      error: function(err) {
        console.log(err)
      },
    })
  })


  $('.del-btns').on('click', function(e) {
    console.log("clicked")
    e.preventDefault();
    $.ajax({
      url: `listings/${e.target.id}`,
      method: 'delete',
      dataType: 'JSON',
      success: function(data) {
        console.log(data);

        const imgUrl = data.url

        $('#image-show').append(`<img src="${imgUrl}"/>`) 
      },
      error: function(err) {
        console.log(err)
      },
    })
  })

  $('#query').on("keyup", function(){
    autocomplete()
  });


  function autocomplete(){
    let query = $("#query").serialize();
    console.log(query);

    $.ajax({
      url:'/search',
      type:'POST',
      data: $("#form").serialize(),
      dataType:'json',
      error: function(request, status, error){
        console.log(request.responseText);
                // console.log(request.responseText);
        console.log("sorry. Something went wrong")
      },
      success: function(data){

        Array.prototype.unique = function() {
          return this.filter(function (value, index, self) { 
            return self.indexOf(value) === index;
          });
        }
        console.log(data);
        console.log(data.unique());
        $("#list").html("");
        data.unique().forEach(function(element){
          var option = document.createElement("option");
          option.value = element;
          // console.log(option);
        
          var list = $("#list");
          list.append(option);
         $('#optionVal').val(option);
          console.log(list);
        });
      }
    });
  }
</script>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/preview.html.erb
 <%=image_tag(@listing.property[0].thumb.url, width:1100, height:500) if @listing.property?%>
<br>
<%= link_to 'Back', listings_path %>

app/views/listings/preview.js.erb
console.log("preview works")

var img = "<%= j image_tag(@listing.property[0].thumb.url, width:1100, height:500) if @listing.property?%>"

$('#image-show').append(img)

app/views/listings/search.html.erb
 <h3 id="location">Enter the location that you looking for</h3>


    <%= form_tag '/search', method: 'post', :id => 'form', :class => 'form-inline my-2 my-lg-0' do %>
     <%= text_field_tag :query, "", :class =>'form-control mr-sm-2', list: "list" %>
     <datalist id="list"> 
    </datalist>
      <%= submit_tag "Search",:id => 'searchBtn',:class => 'btn btn-outline-primary my-2 my-sm-0'%>
      <% end %>

<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Property type</th>
      <th>Room number</th>
      <th>Bed number</th>
      <th>Guest number</th>
      <th>Country</th>
      <th>State</th>
      <th>City</th>
      <th>Zipcode</th>
      <th>Address</th>
      <th>Price</th>
      <th>Description</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if current_user.moderator?%>
      <% @list.order('verification asc').each do |listing| %>
        <tr>
            
            <td><%= listing.name %></td>
            <td><%= listing.property_type %></td>
            <td><%= listing.room_number %></td>
            <td><%= listing.bed_number %></td>
            <td><%= listing.guest_number %></td>
            <td><%= listing.country %></td>
            <td><%= listing.state %></td>
            <td><%= listing.city %></td>
            <td><%= listing.zipcode %></td>
            <td><%= listing.address %></td>
            <td><%= listing.price %></td>
            <td><%= listing.description %></td>

            <td><%= link_to 'Show', listing %></td>
            <% if listing.verification == false%>
            <td><%= button_to 'Verification',"/listings/#{listing.id}/verify", method: :post%></td>
            <%end%>
      <%end%>

    <%else%>
        <% @list.order('id asc').each do |listing| %>
          <%if listing.verification == true%>
        <tr>
            <td><%= listing.name %></td>
            <td><%= listing.property_type %></td>
            <td><%= listing.room_number %></td>
            <td><%= listing.bed_number %></td>
            <td><%= listing.guest_number %></td>
            <td><%= listing.country %></td>
            <td><%= listing.state %></td>
            <td><%= listing.city %></td>
            <td><%= listing.zipcode %></td>
            <td><%= listing.address %></td>
            <td><%= listing.price %></td>
            <td><%= listing.description %></td>

            
            <td><%= link_to 'Show', listing %></td>
            <td><%=link_to 'Preview', "/listings/#{listing.id}/preview", method: :post%>
            <%if current_user.id == listing.user_id %>
            <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
            <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }%></td>
            <%elsif current_user.admin?%>
            <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <%end%>
            
          </tr>
        <% end %>
      <%end%>
    <%end%>
    
  </tbody>
</table>

<br>
<% if current_user.customer?%>
<%= link_to 'New Listing', new_listing_path %>
<%end%>

app/views/listings/show.html.erb
  
  <%if @listing.property?%>
  <div id="demo" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    
  </ul>
  
  <!-- The slideshow -->
  <div class="carousel-inner">
  <%@listing.property.each_with_index do |x, index|%>
     <%if index ==0 %>
      <div class="carousel-item active">
      <%else%>
        <div class="carousel-item">
      <%end%>

      <%=image_tag x.url, width:800, height:500, :class => "listing-photo"%>
        </div>
  <%end%>

      <%#=image_tag(@listing.property[0].thumb.url, width:1100, height:500) if @listing.property?%>
    
      <%#=image_tag(@listing.property[1].thumb.url, width:1100, height:500) if @listing.property?%>
 
    
      </div>
  </div>
  
  <!-- Left and right controls -->
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
  <%end%>
</div>

<p>
  <strong>Name:</strong>
  <%= @listing.name %>
</p>

<p>
  <strong>Property type:</strong>
  <%= @listing.property_type %>
</p>

<p>
  <strong>Room number:</strong>
  <%= @listing.room_number %>
</p>

<p>
  <strong>Bed number:</strong>
  <%= @listing.bed_number %>
</p>

<p>
  <strong>Guest number:</strong>
  <%= @listing.guest_number %>
</p>

<p>
  <strong>Country:</strong>
  <%= @listing.country %>
</p>

<p>
  <strong>State:</strong>
  <%= @listing.state %>
</p>


<p>
  <strong>City:</strong>
  <%= @listing.city %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @listing.zipcode %>
</p>

<p>
  <strong>Address:</strong>
  <%= @listing.address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>


<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>






<%if current_user.id == @listing.user_id%>
<%= link_to 'Edit', edit_listing_path(@listing) %> 
<%end%>
<%= link_to 'Reservation', "/listings/#{@listing.id}/reservation/new" %><br>
<%= link_to 'Back', listings_path %>