config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'

  get 'welcome/index'

  resources :listings, controller: "listings"
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create,:profile] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  # get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  # delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  # get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

post 'braintree/:id' => "braintree#checkout"
get 'braintree/:id' => "braintree#new"

get "/reservation" => "reservations#index"
get "/listings/:id/reservation/new" => "reservations#new"
get "reservation/host" => "reservations#find"
post "/listings/:id/reservation/new" => "reservations#create"


post "/profile/edit" => "users#update"
get "/profile" => 'users#edit'
get "/listings/:id/preview" => "listings#preview"
post "/listings/:id" => "listings#show"
post "/listings/:id/verify" => "listings#verify"
get "/auth/:provider/callback" => "sessions#create_from_omniauth"

post "/search" => "listings#search"

##this is to link to google for sign in with google
root to: "home#index"
##this is to point the rootpage to view/home/index.. every time to create a view, need to create a controller. 
##home is the class while index is the method. the naming should be the same for the views folder
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [ :customer, :admin, :moderator]
   mount_uploaders :image, ImageUploader
   
   
  include Clearance::User

   has_many :authentications, dependent: :destroy
   has_many :reservations
   has_many :listings
   

 def self.create_with_auth_and_hash(authentication, auth_hash)
   user = self.create!(
     first_name: auth_hash["info"]["first_name"],
     last_name: auth_hash["info"]["last_name"],
     email: auth_hash["info"]["email"],
     password: SecureRandom.hex(10)
   
   )
   user.authentications << authentication
   return user
 end

 # grab google to access google for user data
 def google_token
   x = self.authentications.find_by(provider: 'google_oauth2')
   return x.token unless x.nil?
 end
  

end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  def edit
    @user= current_user

  end


  def update
    @user = current_user
    @user.update(permit_params)

    redirect_to profile_path

    end


  def user_from_params
    user_params = params[:user] || Hash.new
    email = user_params.delete(:email)
    password = user_params.delete(:password)
    first_name = user_params.delete(:first_name)
    last_name = user_params.delete(:last_name)
    birthday = user_params.delete(:birthday)
    image = user_params.delete(:image)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
      user.first_name = first_name
      user.last_name = last_name
      user.birthday = birthday
      user.image = image
  	end
    end

    def permit_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :birthday, {image: []})
  	end
  end

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.email_field :email%>
</div>

<div class="text-field">
  <%= form.label :first_name %>
  <%= form.text_field :first_name%>
</div>

<div class="text-field">
  <%= form.label :last_name%>
  <%= form.text_field :last_name %>
</div>

<div class="text-field">
  <%= form.label :birthday %>
  <%= form.date_field :birthday %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

<div class="field">
    <%= form.label :image %>
    <%= form.file_field :image,multiple: true %>
  </div>

app/views/users/edit.html.erb
<%=image_tag(@user.image[0].thumb.url,:class => "profile-photo1") if @user.image?%>
<br>
<br>

<strong class="title">Email</strong>
<h4 class="content"><%=@user.email%></h4>
<br>
<br>

<%= form_for(@user, url: profile_edit_path, html: {method: "post"}) do |form| %> 
<!-- <%#=form_for :user, url: "/profile/edit",action: :update, method: :post do |form|%> -->
<strong class="title">First Name</strong>
<h4 class="content"><%=form.text_field :first_name, :value => @user.first_name %></h4>
<br>
<br>
<strong class="title">Last Name</strong>
<h4 class="content"><%=form.text_field :last_name, :value => @user.last_name %></h4>
<br>
<br>
<strong class="title">Birthday</strong>
<h4 class="content"><%=form.date_field :birthday, :value => @user.birthday %></h4>
<br>
<br>
<strong class="title">Profile Photo</strong>
<h4 class="content"><%=form.file_field :image, multiple:true %></h4>


<%=form.submit 'Update'%>
<%end%>
<br>
<%= link_to 'Reset Password', "users/#{@user.id}/password/edit" %> 

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>

    <%= link_to "Sign in with Google", "/auth/google_oauth2" %>
  <% end %>
</div>